Team2 task20 patch1
RyanWri/data-science2-lab-final-project pull request #49
Opened 2024-09-04 09:13 UTC by Soncity2

updated task 20 + team readme

2024-09-04 16:32 UTC, RyanWri requested changes
Please review my comments

2024-09-04 16:32 UTC, RyanWri commented on src/team_2/README.md
> +| Task ID | Description                                                        | Status                                   | Progress                        |
write conclusions instead, the project already track the issues

2024-09-04 16:32 UTC, RyanWri commented on src/team_2/task_20/hDoctor_columns.json
> +{
move translation files to translations folder (create one if you don't have)

2024-09-04 16:32 UTC, RyanWri commented on src/team_2/task_9/task_9.py
> +import os
duplicate code, import function from relevant packages (team 1 i.e)

2024-09-06 10:06 UTC, Soncity2 commented
Edited the Requested changes, wasn't able to run the code because of updated repo not pulled

2024-09-06 16:12 UTC, RyanWri approved these changes
Approved

2024-09-06 18:31 UTC, merged